import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Text } from '@chakra-ui/react'
import Link from 'next/link'

export default function Home({post}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Text bg={'red.400'} fontSize={'3xl'} textAlign={'center'}>Hello it is from chakra ui</Text>
        <Link href={'login'}>Login</Link>
        {post.map((data) => {
        return (
      <li key={data.id}>{data.title}</li>
      )})}
      </main>
    </>
  )
}


export async function getServerSideProps(context) {
  const res=await fetch('http://localhost:3000/api/hello')
  const data=await res.json()
  return {
    props: {post:data}, // will be passed to the page component as props
  }
}
