import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles1 from '@/styles/Home.module.css'
import styles2 from '@/styles/main.module.css'
import { Box, Container, Input, InputGroup, InputLeftElement, Text } from '@chakra-ui/react'
import Link from 'next/link'
import React, { useState } from 'react'
import Loding from '@/components/Loding'
import { Search2Icon } from '@chakra-ui/icons'

export default function Home({ post }) {
    const [loading, setloading] = useState(false)
    const [search, setsearch] = useState()

    const handleSubmit = async (e) => {
        setsearch(e.target.value)
        setloading(true)
    }
    let list = [1, 2, 3, 4]
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles1.mainPage}>
                <Box m={'auto'} width={'80%'} position={'relative'} top='70px'>

                    <nav className={styles1.nav}>
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </nav>
                    <div className={styles1.postQuery}>
                        <InputGroup border='1px' borderRadius={'8px'} >
                            <InputLeftElement
                                pointerEvents="none"
                                children={<Search2Icon color="gray.300" />}
                            />
                            <Input type="text" placeholder='Enter your query' value={search} onChange={handleSubmit} required />
                        </InputGroup>
                        <div className={styles1.center}>
                        <div className={styles2.title}>
                            This is Our Title of post.........
                            <div className={styles2.title_innerbox}>
                                <div className={styles2.title_innerboxbox}>Asked</div>
                                <div className={styles2.title_innerboxbox}>modifid</div>
                                <div className={styles2.title_innerboxbox}>views</div>
                            </div>
                        </div>
                        <div className={styles2.showQuery}>
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box                             this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box                             this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box  this is you box  this is you box  this is you box  this is you box 
                            this is you box
                            this is you box
                            this is you box
                        </div>
                        </div>
                        {loading && <Loding />}
                    </div>
                </Box>
            </main>

        </>
    )
}


export async function getServerSideProps(context) {
    const res = await fetch('http://localhost:3000/api/hello')
    const data = await res.json()
    return {
        props: { post: data }, // will be passed to the page component as props
    }
}
